apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: web
          image: traefik/whoami:v1.10.3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: live
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
