apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-errors
  namespace: traefik-private
spec:
  errors:
    status:
      - "403"
    service:
      name: private-404
      port: 80
    query: /
