apiVersion: v1
kind: ConfigMap
metadata:
  name: error-pages-nginx
  namespace: live
data:
  default.conf: |
    server {
      listen 80;
      location / {
        return 404 "Not Found\n";
      }
      location = /404.html {
        return 200 "Not Found\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
  namespace: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: error-pages-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
  namespace: live
spec:
  selector:
    app: error-pages
  ports:
    - name: http
      port: 80
      targetPort: 80
