apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wireguard
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # 게이트웨이 노드 1대에만 고정(추천)
      nodeSelector:
        vpn-gw: "true"

      containers:
        - name: wireguard
          image: ghcr.io/linuxserver/wireguard:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Seoul"
          ports:
            - name: wg
              containerPort: 51820
              hostPort: 51820
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: modules
              mountPath: /lib/modules
              readOnly: true
          # linuxserver/wireguard는 /config/wg_confs/wg0.conf 를 읽는 방식이 일반적입니다.
          # 아래 initContainer가 wg0.conf를 그 위치로 만들어줍니다.

      initContainers:
        - name: render-config
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - sh
            - -lc
            - |
              set -e
              mkdir -p /config/wg_confs
              SERVER_KEY="$(cat /keys/server.key)"
              sed "s|__SERVER_PRIVATE_KEY__|$SERVER_KEY|g" /tmpl/wg0.conf > /config/wg_confs/wg0.conf
              chmod 600 /config/wg_confs/wg0.conf
          volumeMounts:
            - name: config
              mountPath: /config
            - name: keys
              mountPath: /keys
              readOnly: true
            - name: tmpl
              mountPath: /tmpl
              readOnly: true

      volumes:
        - name: config
          hostPath:
            path: /var/lib/wireguard
            type: DirectoryOrCreate
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: keys
          secret:
            secretName: wireguard-keys
        - name: tmpl
          configMap:
            name: wireguard-config
            items:
              - key: wg0.conf
                path: wg0.conf
