apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-public
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - hello.creco.dev
      secretName: hello-creco-dev-tls
  rules:
    - host: hello.creco.dev
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: hello
                port:
                  number: 80
