apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-allow-internal
  namespace: traefik-private
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.0/16
      - 10.0.0.0/8
      - 100.64.0.0/10
